nvchecker.toml

Add a tracker for `python-mkl-random` from AUR.

Add python-mkl-random

---

nvchecker.toml

Add a tracker for `petsc-complex` from AUR. Later we will check about makedependencies (working in progress).

Add PETSc (complex scalars)

---

nvchecker.toml

Add a tracker for `python-imread` from AUR.

Add python-imread

---

nvchecker.toml

Add a tracker for python-url-normalize from AUR.

Add python-url-normalize

---

nvchecker.toml

Add a tracker for `python-requests-cache` from AUR.

Add python-requests-cache

---

nvchecker.toml

Add a tracker for `python-pywavelets` from AUR.

Add python-pywavelets

---

nvchecker.toml

Add a tracker for `python-pydub` from AUR.

Add python-pydub

---

nvchecker.toml

Add a tracker for `superlu_dist` from AUR.

Add superlu_dist

---

nvchecker.toml

This pull request is used to test a new workflow.

Add python-mkl-service

---

nvchecker.toml

This pull request is enabling watching new versions https://repo.anaconda.com/archive, other way could be from https://anaconda.org/anaconda/anaconda

Add anaconda

---

nvchecker.toml

This pull request is enabling watching new versions from https://github.com/FEniCS for `dolfinx` family.

Add python-fenics-dolfinx

---

nvchecker.toml

Adding pixlet-bin, a simple binary package served by GitHub.

Adding pixlet-bin.

---

nvchecker.toml

Add tube-converter and gnome-shell-extension-background-logo
Fixes #27

Add tube-converter and gnome-shell-extension-background-logo

---

config/carlosal1015/anaconda.yaml
config/carlosal1015/basix.yaml
config/carlosal1015/calcmysky.yaml
config/carlosal1015/dolfinx.yaml
config/carlosal1015/hypre.yaml
config/carlosal1015/kahip.yaml
config/carlosal1015/libxc.yaml
config/carlosal1015/petsc-complex.yaml
config/carlosal1015/python-fenics-basix.yaml
config/carlosal1015/python-fenics-dolfinx.yaml
config/carlosal1015/python-fenics-ffcx.yaml
config/carlosal1015/python-fenics-ufl.yaml
config/carlosal1015/python-imread.yaml
config/carlosal1015/python-mkl-random.yaml
config/carlosal1015/python-multiprocess.yaml
config/carlosal1015/python-pydotplus.yaml
config/carlosal1015/python-pydub.yaml
config/carlosal1015/python-pywavelets.yaml
config/carlosal1015/python-requests-cache.yaml
config/carlosal1015/python-url-normalize.yaml
config/carlosal1015/superlu_dist.yaml

update config for carlosal1015

---

config/Freso/stavekontrolden.yaml

https://aur.archlinux.org/packages/stavekontrolden

Add stavekontrolden

---

config/Freso/obs-vertical-canvas.yaml

https://aur.archlinux.org/packages/obs-vertical-canvas

Add obs-vertical-canvas

---

config/Freso/chatty-beta.yaml
config/Freso/chatty.yaml

https://aur.archlinux.org/pkgbase/chatty
https://aur.archlinux.org/pkgbase/chatty-beta

Track chatty{,-beta} packages

---

config/Freso/wootility-appimage.yaml
config/Freso/wootility3-appimage.yaml

https://aur.archlinux.org/packages/wootility-appimage
https://aur.archlinux.org/packages/wootility3-appimage

Track wootility{,3}-appimage packages

---

config/feydreva/winamax-bin.yaml

Hello, 
1st time doing this, please be kind

Adding winamax-bin.yaml

---

config/Freso/obs-pipewire-audio-capture.yaml

https://aur.archlinux.org/pkgbase/obs-pipewire-audio-capture

Add obs-pipewire-audio-capture

---

config/alllexx88/zapzap.yaml

Hi, I just adopted `zapzap`, this commit adds it back. Thanks.

Readd `zapzap`

---

config/Freso/protonhax.yaml
config/Freso/python-librivox.yaml
config/Freso/python-onion-location.yaml
config/Freso/steamtokendumper-bin.yaml

https://aur.archlinux.org/pkgbase/protonhax
https://aur.archlinux.org/pkgbase/steamtokendumper-bin
https://aur.archlinux.org/pkgbase/python-librivox
https://aur.archlinux.org/pkgbase/python-onion-location

Add protonhax, steamtokendumper-bin, and python-librivox

---

config/anispwyn/sleepy-launcher.yaml

https://aur.archlinux.org/packages/sleepy-launcher-bin

add eppy-launcher-bin

---

config/jclds139/aocl-utils.yaml
config/jclds139/nodejs-tiddlywiki.yaml
config/jclds139/python-zlib-ng.yaml
config/jclds139/visual-studio-code-cli-bin.yaml

Add the following packages which I maintain:
- `visual-studio-code-cli-bin`
- `aocl-utils`
- `python-zlib-ng`
- `nodejs-tiddlywiki`

Add 4 packages
